name: Linting

on: pull_request

jobs:
  swiftformat:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: brew update && brew upgrade swiftformat
    - name: swiftformt
      run: |
         swiftformat --lint .

  swiftlint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: brew update && brew upgrade swiftlint
    - name: swiftlint
      run: |
         swiftlint --strict
