name: Testing

on: pull_request

jobs:
  testing:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing packages
      run: |
        brew install libtool automake cmake carthage go@1.14 swiftlint swiftformat
        gem install bundler
        bundle install
    - uses: actions/cache@v2
      id: carthage-cache
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-
    - uses: actions/cache@v2
      id: pods-cache
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Carthage
      if: steps.carthage-cache.outputs.cache-hit != 'true'
      run: ./scripts/wcarthage bootstrap --platform iOS --no-use-binaries --cache-builds
    - name: Cocoapods
      if: steps.pods-cache.outputs.cache-hit != 'true'
      run: bundle exec pod install
    - name: GopenPGP
      run: |
        export PATH="/usr/local/opt/go@1.14/bin:$PATH"
        ./scripts/gopenpgp_build.sh
    - name: Testing
      run: bundle exec fastlane test
